def keywords():
    init_keywords = [
        ('elections', 1),
        ('government', 1),
        ('legislation', 1),
        ('diplomacy', 1),
        ('campaigns', 1),
        ('political parties', 1),
        ('policies', 1),
        ('voting', 1),
        ('corruption', 1),
        ('national security', 1),
        ('finance', 2),
        ('stock market', 2),
        ('startups', 2),
        ('industry', 2),
        ('global economy', 2),
        ('corporate profits', 2),
        ('trade agreements', 2),
        ('employment rates', 2),
        ('market trends', 2),
        ('entrepreneurship', 2),
        ('artificial intelligence', 3),
        ('robotics', 3),
        ('cybersecurity', 3),
        ('cloud computing', 3),
        ('internet of things', 3),
        ('virtual reality', 3),
        ('machine learning', 3),
        ('5g', 3),
        ('blockchain', 3),
        ('automation', 3),
        ('film', 4),
        ('music', 4),
        ('television', 4),
        ('celebrities', 4),
        ('awards', 4),
        ('fashion', 4),
        ('theater', 4),
        ('art', 4),
        ('books', 4),
        ('gaming', 4),
        ('football', 5),
        ('basketball', 5),
        ('soccer', 5),
        ('tennis', 5),
        ('baseball', 5),
        ('olympics', 5),
        ('golf', 5),
        ('boxing', 5),
        ('running', 5),
        ('swimming', 5),
        ('medicine', 6),
        ('nutrition', 6),
        ('mental health', 6),
        ('exercise', 6),
        ('vaccines', 6),
        ('pandemics', 6),
        ('cancer', 6),
        ('obesity', 6),
        ('aging', 6),
        ('wellness', 6),
        ('space exploration', 7),
        ('climate change', 7),
        ('genetics', 7),
        ('energy', 7),
        ('ecology', 7),
        ('nature', 7),
        ('physics', 7),
        ('chemistry', 7),
        ('biology', 7),
        ('neurosience', 7),
        ('k-12 education', 8),
        ('higher education', 8),
        ('distance learning', 8),
        ('student debt', 8),
        ('teacher shortages', 8),
        ('education policy', 8),
        ('standardized testing', 8),
        ('STEM education', 8),
        ('liberal arts', 8),
        ('vocal training', 8),
        ('pollution', 9),
        ('climate change', 9),
        ('remnewable energy', 9),
        ('wildlife conservation', 9),
        ('sustainable development', 9),
        ('natural disasters', 9),
        ('green technology', 9),
        ('ocean conservation', 9),
        ('air quality', 9),
        ('water scarcity', 9),
        ('food', 10),
        ('travel', 10),
        ('relationships', 10),
        ('fashion', 10),
        ('parenting', 10),
        ('pets', 10),
        ('hobbies', 10),
        ('culture', 10),
        ('excersice', 10),
        ('retirement', 10),
    ]
    return init_keywords


def categories():
    init_categories = [
        ('politics',),
        ('business',),
        ('technology',),
        ('entertainment',),
        ('sports',),
        ('health',),
        ('science',),
        ('education',),
        ('environment',),
        ('lifestyle',)]
    return init_categories


def phrases():
    init_phrases = [
        'extreme temperature',
        'drought',
        'Inflation',
        'interest rate',
        'natural resources'
        ]
    return init_phrases
